<Project>
  <PropertyGroup>
    <Version>0.4.2</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'ProjectBeacon.Domain' AND '$(MSBuildProjectName)' != 'ProjectBeacon.Domain.Tests' AND '$(MSBuildProjectName)' != 'ProjectBeacon.Infrastructure' AND '$(MSBuildProjectName)' != 'ProjectBeacon.Cli' AND '$(MSBuildProjectName)' != 'ProjectBeacon.Cli.Tests'">
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
</Project>
