packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  better-sqlite3: true
  esbuild: true
  tree-sitter: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-typescript: true

catalog:
  eslint: ^9.39.1
  prettier: ^3.6.2
  typescript: ^5.9.3
  typescript-eslint: ^8.46.4
  "@eslint/js": ^9.39.1
