using MudBlazor;

namespace ProjectBeacon.Web.Theme;

public static class BeaconTheme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = new PaletteLight
        {
            Background = "#f4f4f5",
            Surface = "#ffffff",
            TextPrimary = "#18181b",
            TextSecondary = "#71717a",
            TextDisabled = "#a1a1aa",
            LinesDefault = "#e4e4e7",
            Primary = "#2563eb",
            PrimaryContrastText = "#fafafa",
            Info = "#2563eb",
            InfoContrastText = "#fafafa",
            Error = "#dc2626",
            ErrorContrastText = "#fafafa",
            Warning = "#d97706",
            WarningContrastText = "#1c1403",
            Success = "#059669",
            SuccessContrastText = "#000000",
            AppbarBackground = "#f4f4f5",
            AppbarText = "#18181b",
            DrawerBackground = "#f4f4f5",
            DrawerText = "#3f3f46",
            DrawerIcon = "#71717a",
        },
        PaletteDark = new PaletteDark
        {
            Black = "#0c0c0c",
            White = "#f5f5f5",
            Background = "#181818",
            BackgroundGray = "#141414",
            Surface = "#1A1A1A",
            TextPrimary = "#F5F5F5",
            TextSecondary = "#B5B5B5",
            TextDisabled = "#5C5C5C",
            ActionDefault = "#8A8A8A",
            ActionDisabled = "#5C5C5C",
            ActionDisabledBackground = "#202020",
            LinesDefault = "#2A2A2A",
            LinesInputs = "#2A2A2A",
            TableLines = "#2A2A2A",
            TableHover = "#202020",
            Divider = "#2A2A2A",
            DividerLight = "#222222",
            OverlayDark = "rgba(0,0,0,0.62)",
            OverlayLight = "rgba(24,24,24,0.5)",
            Primary = "#3B82F6",
            PrimaryContrastText = "#0b1220",
            PrimaryDarken = "#2563EB",
            PrimaryLighten = "#60A5FA",
            Secondary = "#3f3f46",
            SecondaryContrastText = "#f5f5f5",
            Info = "#60A5FA",
            InfoContrastText = "#0b1220",
            InfoDarken = "#3B82F6",
            InfoLighten = "#93C5FD",
            Success = "#34d399",
            SuccessContrastText = "#022c22",
            SuccessDarken = "#10b981",
            SuccessLighten = "#6ee7b7",
            Warning = "#fbbf24",
            WarningContrastText = "#1c1403",
            WarningDarken = "#d97706",
            WarningLighten = "#fcd34d",
            Error = "#f87171",
            ErrorContrastText = "#1c0808",
            ErrorDarken = "#ef4444",
            ErrorLighten = "#fca5a5",
            Dark = "#171717",
            DarkContrastText = "#F5F5F5",
            AppbarBackground = "#181818",
            AppbarText = "#F5F5F5",
            DrawerBackground = "#141414",
            DrawerText = "#B5B5B5",
            DrawerIcon = "#8A8A8A",
            GrayDefault = "#8A8A8A",
            GrayLight = "#5C5C5C",
            GrayLighter = "#2A2A2A",
            GrayDark = "#B5B5B5",
            GrayDarker = "#F5F5F5",
        },
        LayoutProperties = new LayoutProperties
        {
            DefaultBorderRadius = "12px",
            AppbarHeight = "64px",
            DrawerWidthLeft = "240px",
        },
        ZIndex = new ZIndex()
        {
            AppBar = 1100,
            Drawer = 1200,
            Popover = 1400,
        },
    };
}
