using MudBlazor;

namespace ProjectBeacon.Web.Theme;

public static class BeaconTheme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = Light(),
        PaletteDark = Dark(),
        LayoutProperties = new LayoutProperties
        {
            DefaultBorderRadius = DesignTokens.RadiusSmall,
            AppbarHeight = "68px",
            DrawerWidthLeft = "236px",
        },
        ZIndex = new ZIndex
        {
            AppBar = 1100,
            Drawer = 1200,
            Popover = 1400,
        },
    };

    private static PaletteLight Light() => new()
    {
        Black = "#10141c",
        White = "#ffffff",
        Background = DesignTokens.BgApp,
        BackgroundGray = DesignTokens.Surface1,
        Surface = DesignTokens.Surface2,
        TextPrimary = DesignTokens.TextPrimary,
        TextSecondary = DesignTokens.TextSecondary,
        TextDisabled = DesignTokens.TextDisabled,
        ActionDefault = DesignTokens.TextMuted,
        ActionDisabled = DesignTokens.TextDisabled,
        ActionDisabledBackground = DesignTokens.Surface3,
        LinesDefault = DesignTokens.Border,
        LinesInputs = DesignTokens.BorderStrong,
        TableLines = DesignTokens.Border,
        TableHover = DesignTokens.Surface1,
        Divider = DesignTokens.Border,
        DividerLight = DesignTokens.BorderSubtle,
        OverlayDark = "rgba(5,8,12,.58)",
        OverlayLight = "rgba(243,245,247,.72)",
        Primary = DesignTokens.Accent,
        PrimaryContrastText = "#ffffff",
        PrimaryDarken = DesignTokens.AccentHover,
        PrimaryLighten = "#8883ff",
        Secondary = DesignTokens.Surface3,
        SecondaryContrastText = DesignTokens.TextPrimary,
        Info = DesignTokens.Info,
        InfoContrastText = "#ffffff",
        InfoDarken = "#1d5fa3",
        InfoLighten = "#70abe6",
        Success = DesignTokens.Success,
        SuccessContrastText = "#ffffff",
        SuccessDarken = "#0f6b52",
        SuccessLighten = "#52c69f",
        Warning = DesignTokens.Warning,
        WarningContrastText = "#ffffff",
        WarningDarken = "#8a560c",
        WarningLighten = "#e0a64c",
        Error = DesignTokens.Danger,
        ErrorContrastText = "#ffffff",
        ErrorDarken = "#b33d44",
        ErrorLighten = "#ef747b",
        Dark = DesignTokens.Sidebar,
        DarkContrastText = DesignTokens.SidebarTextStrong,
        AppbarBackground = DesignTokens.BgHeader,
        AppbarText = DesignTokens.TextPrimary,
        DrawerBackground = DesignTokens.Sidebar,
        DrawerText = DesignTokens.SidebarText,
        DrawerIcon = DesignTokens.SidebarText,
        GrayDefault = DesignTokens.TextMuted,
        GrayLight = DesignTokens.TextDisabled,
        GrayLighter = DesignTokens.Border,
        GrayDark = DesignTokens.TextSecondary,
        GrayDarker = DesignTokens.TextPrimary,
    };

    private static PaletteDark Dark() => new()
    {
        Black = "#0c0c0c",
        White = "#f5f5f5",
        Background = "#181818",
        BackgroundGray = "#141414",
        Surface = "#1A1A1A",
        TextPrimary = "#F5F5F5",
        TextSecondary = "#B5B5B5",
        TextDisabled = "#5C5C5C",
        ActionDefault = "#8A8A8A",
        ActionDisabled = "#5C5C5C",
        ActionDisabledBackground = "#202020",
        LinesDefault = "#2A2A2A",
        LinesInputs = "#2A2A2A",
        TableLines = "#2A2A2A",
        TableHover = "#202020",
        Divider = "#2A2A2A",
        DividerLight = "#222222",
        OverlayDark = "rgba(0,0,0,0.62)",
        OverlayLight = "rgba(24,24,24,0.5)",
        Primary = "#3B82F6",
        PrimaryContrastText = "#0b1220",
        PrimaryDarken = "#2563EB",
        PrimaryLighten = "#60A5FA",
        Secondary = "#3f3f46",
        SecondaryContrastText = "#f5f5f5",
        Info = "#60A5FA",
        InfoContrastText = "#0b1220",
        InfoDarken = "#3B82F6",
        InfoLighten = "#93C5FD",
        Success = "#34d399",
        SuccessContrastText = "#022c22",
        SuccessDarken = "#10b981",
        SuccessLighten = "#6ee7b7",
        Warning = "#fbbf24",
        WarningContrastText = "#1c1403",
        WarningDarken = "#d97706",
        WarningLighten = "#fcd34d",
        Error = "#f87171",
        ErrorContrastText = "#1c0808",
        ErrorDarken = "#ef4444",
        ErrorLighten = "#fca5a5",
        Dark = "#171717",
        DarkContrastText = "#F5F5F5",
        AppbarBackground = "#181818",
        AppbarText = "#F5F5F5",
        DrawerBackground = "#141414",
        DrawerText = "#B5B5B5",
        DrawerIcon = "#8A8A8A",
        GrayDefault = "#8A8A8A",
        GrayLight = "#5C5C5C",
        GrayLighter = "#2A2A2A",
        GrayDark = "#B5B5B5",
        GrayDarker = "#F5F5F5",
    };
}
