using MudBlazor;

namespace ProjectBeacon.Web.Theme;
/// <summary>
/// MudBlazor theme. Colors and geometry come from DesignTokens.
/// </summary>
public static class BeaconTheme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = Light(),
        PaletteDark = Dark(),
        LayoutProperties = new LayoutProperties
        {
            DefaultBorderRadius = DesignTokens.RadiusSmall,
            AppbarHeight = "80px",
            DrawerWidthLeft = "236px",
        },
        ZIndex = new ZIndex
        {
            AppBar = 1100,
            Drawer = 1200,
            Popover = 1400,
        },
    };

    private static PaletteLight Light() => new()
    {
        Black = "#10141c",
        White = "#ffffff",
        Background = DesignTokens.BgApp,
        BackgroundGray = DesignTokens.Surface1,
        Surface = DesignTokens.Surface2,
        TextPrimary = DesignTokens.TextPrimary,
        TextSecondary = DesignTokens.TextSecondary,
        TextDisabled = DesignTokens.TextDisabled,
        ActionDefault = DesignTokens.TextMuted,
        ActionDisabled = DesignTokens.TextDisabled,
        ActionDisabledBackground = DesignTokens.Surface3,
        LinesDefault = DesignTokens.Border,
        LinesInputs = DesignTokens.BorderStrong,
        TableLines = DesignTokens.Border,
        TableHover = DesignTokens.Surface1,
        Divider = DesignTokens.Border,
        DividerLight = DesignTokens.BorderSubtle,
        OverlayDark = "rgba(5,8,12,.58)",
        OverlayLight = "rgba(243,245,247,.72)",
        Primary = DesignTokens.Accent,
        PrimaryContrastText = "#ffffff",
        PrimaryDarken = DesignTokens.AccentHover,
        PrimaryLighten = "#8883ff",
        Secondary = DesignTokens.Surface3,
        SecondaryContrastText = DesignTokens.TextPrimary,
        Info = DesignTokens.Info,
        InfoContrastText = "#ffffff",
        InfoDarken = "#1d5fa3",
        InfoLighten = "#70abe6",
        Success = DesignTokens.Success,
        SuccessContrastText = "#ffffff",
        SuccessDarken = "#0f6b52",
        SuccessLighten = "#52c69f",
        Warning = DesignTokens.Warning,
        WarningContrastText = "#ffffff",
        WarningDarken = "#8a560c",
        WarningLighten = "#e0a64c",
        Error = DesignTokens.Danger,
        ErrorContrastText = "#ffffff",
        ErrorDarken = "#b33d44",
        ErrorLighten = "#ef747b",
        Dark = DesignTokens.Sidebar,
        DarkContrastText = DesignTokens.SidebarTextStrong,
        AppbarBackground = DesignTokens.BgHeader,
        AppbarText = DesignTokens.TextPrimary,
        DrawerBackground = DesignTokens.Sidebar,
        DrawerText = DesignTokens.SidebarText,
        DrawerIcon = DesignTokens.SidebarText,
        GrayDefault = DesignTokens.TextMuted,
        GrayLight = DesignTokens.TextDisabled,
        GrayLighter = DesignTokens.Border,
        GrayDark = DesignTokens.TextSecondary,
        GrayDarker = DesignTokens.TextPrimary,
    };

    private static PaletteDark Dark() => new()
    {
        Black = "#0a0d12",
        White = "#edf0f5",
        Background = DesignTokens.Dark.BgApp,
        BackgroundGray = DesignTokens.Dark.Surface1,
        Surface = DesignTokens.Dark.Surface2,
        TextPrimary = DesignTokens.Dark.TextPrimary,
        TextSecondary = DesignTokens.Dark.TextSecondary,
        TextDisabled = DesignTokens.Dark.TextDisabled,
        ActionDefault = DesignTokens.Dark.TextMuted,
        ActionDisabled = DesignTokens.Dark.TextDisabled,
        ActionDisabledBackground = DesignTokens.Dark.Surface3,
        LinesDefault = DesignTokens.Dark.Border,
        LinesInputs = DesignTokens.Dark.BorderStrong,
        TableLines = DesignTokens.Dark.Border,
        TableHover = DesignTokens.Dark.Surface1,
        Divider = DesignTokens.Dark.Border,
        DividerLight = DesignTokens.Dark.BorderSubtle,
        OverlayDark = "rgba(0,0,0,.62)",
        OverlayLight = "rgba(15,18,24,.72)",
        Primary = DesignTokens.Dark.Accent,
        PrimaryContrastText = "#10141c",
        PrimaryDarken = DesignTokens.Dark.AccentActive,
        PrimaryLighten = DesignTokens.Dark.AccentHover,
        Secondary = DesignTokens.Dark.Surface3,
        SecondaryContrastText = DesignTokens.Dark.TextPrimary,
        Info = DesignTokens.Dark.Info,
        InfoContrastText = "#10141c",
        InfoDarken = "#4d8ec9",
        InfoLighten = "#9cc4ef",
        Success = DesignTokens.Dark.Success,
        SuccessContrastText = "#06281f",
        SuccessDarken = "#2f9a78",
        SuccessLighten = "#7fd4b6",
        Warning = DesignTokens.Dark.Warning,
        WarningContrastText = "#2a1c08",
        WarningDarken = "#b88838",
        WarningLighten = "#ebc07a",
        Error = DesignTokens.Dark.Danger,
        ErrorContrastText = "#2a1013",
        ErrorDarken = "#d25d64",
        ErrorLighten = "#f4a0a5",
        Dark = DesignTokens.Dark.Sidebar,
        DarkContrastText = DesignTokens.SidebarTextStrong,
        AppbarBackground = DesignTokens.Dark.BgHeader,
        AppbarText = DesignTokens.Dark.TextPrimary,
        DrawerBackground = DesignTokens.Dark.Sidebar,
        DrawerText = DesignTokens.SidebarText,
        DrawerIcon = DesignTokens.SidebarText,
        GrayDefault = DesignTokens.Dark.TextMuted,
        GrayLight = DesignTokens.Dark.TextDisabled,
        GrayLighter = DesignTokens.Dark.Border,
        GrayDark = DesignTokens.Dark.TextSecondary,
        GrayDarker = DesignTokens.Dark.TextPrimary,
    };
}
