export const packageName = "@beacon/api-spec";

export {
  ActorRefSchema,
  CommentSchema,
  DecisionSchema,
  ErrorBodySchema,
  ErrorResponseSchema,
  LinkedPathSchema,
  PaginationQuerySchema,
  PatchDecisionSchema,
  ScopeListSchema,
  AnyUuidSchema,
  UuidSchema,
  paginatedResponseSchema,
  type ActorRef,
  type Comment,
  type Decision,
  type ErrorBody,
  type ErrorResponse,
  type LinkedPath,
  type PaginationQuery,
  type PatchDecision,
} from "./common.js";

export {
  ActorTypeSchema,
  ConstraintKindSchema,
  ContextSectionIdSchema,
  DecisionLifecycleStatusSchema,
  DecisionStatusSchema,
  ErrorCodeSchema,
  MilestoneStatusSchema,
  ScopeSchema,
  ScopeTypeSchema,
  TaskStatusSchema,
  TaskTypeSchema,
  TokenizerIdSchema,
  type ActorType,
  type ConstraintKind,
  type ContextSectionId,
  type DecisionLifecycleStatus,
  type DecisionStatus,
  type ErrorCode,
  type MilestoneStatus,
  type Scope,
  type ScopeType,
  type TaskStatus,
  type TaskType,
  type TokenizerId,
} from "./enums.js";

export { toOpenApi } from "./openapi.js";

export {
  BriefBudgetSchema,
  BriefHandoffSchema,
  BriefMilestoneSchema,
  BriefProjectSchema,
  BriefSourceSchema,
  BriefTargetSchema,
  ChangedScopeReasonSchema,
  ChangedScopeSchema,
  CompileExtrasSchema,
  CompileIncludeSchema,
  CompileInputSchema,
  ConstraintViewSchema,
  ContextSectionSchema,
  DEFAULT_TOKENIZER,
  DecisionSummarySchema,
  LintWarningSchema,
  SessionBriefSchema,
  TaskSummarySchema,
  TreeCapsuleEntrySchema,
  TreeCapsuleSchema,
  type BriefHandoff,
  type ChangedScope,
  type CompileInput,
  type ConstraintView,
  type ContextSection,
  type DecisionSummary,
  type LintWarning,
  type SessionBrief,
  type TaskSummary,
  type TreeCapsule,
} from "./session-brief.js";
