using System.Text;

namespace ProjectBeacon.Cli.Client.ModelSwapping;

/// <summary>
/// Splits a command line (the <c>cmd</c> string generated by <c>LlamaSwapConfigGenerator</c>)
/// into an executable path plus argument list, respecting double quotes so paths with spaces
/// survive. Used with <see cref="System.Diagnostics.ProcessStartInfo.ArgumentList"/> — no shell.
/// </summary>
public static class CommandLineSplit
{
    public static (string Exe, string[] Args) Split(string? command)
    {
        var tokens = Tokenize(command ?? "");
        if (tokens.Count == 0)
            return ("", Array.Empty<string>());
        return (tokens[0], tokens.Skip(1).ToArray());
    }

    private static List<string> Tokenize(string s)
    {
        var tokens = new List<string>();
        var sb = new StringBuilder();
        var inQuotes = false;
        var hasToken = false;
        foreach (var c in s)
        {
            if (c == '"')
            {
                inQuotes = !inQuotes;
                hasToken = true;
                continue;
            }
            if (!inQuotes && (c == ' ' || c == '\t'))
            {
                if (hasToken)
                {
                    tokens.Add(sb.ToString());
                    sb.Clear();
                    hasToken = false;
                }
                continue;
            }
            sb.Append(c);
            hasToken = true;
        }
        if (hasToken)
            tokens.Add(sb.ToString());
        return tokens;
    }
}
